version: '2'
services:
  nginx:
    image: 'nginx:latest'
    container_name: 'nginx'
    ports:
      - '80:80'
#    links:
#      - 'mysql:mysql.server.com'
#      - 'mailhog:mail.server.com'
    volumes:
      - './html:/usr/share/nginx/html'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    working_dir: '/code'
    links:
      - 'php:php.server.com'
    environment:
      TERM: xterm

  php:
    image: 'php:7-fpm'
    volumes:
        - './html:/usr/share/nginx/html'
    ports:
      - '9000:9000'
    container_name: 'php'
    environment:
      TERM: xterm

#  mysql:
#    image: 'mysql'
#    container_name: 'mysql'
#    environment:
#      MYSQL_ROOT_PASSWORD: 'paris'
#      MYSQL_DATABASE: 'library'
#      MYSQL_USER: 'acme'
#      MYSQL_PASSWORD: 'paris'
#    volumes:
#      - '/home/aston/Documents/docker-project/mysql/:/root/'

#  pma:
#    image: 'phpmyadmin/phpmyadmin'
#    container_name: 'pma'
#    links:
#      - 'mysql:mysql.server.com'
#    ports:
#      - '81:80'
#    environment:
#      PMA_HOST: 'mysql.server.com'
#
#  mailhog:
#    image: 'mailhog/mailhog'
#    container_name: 'mailhog'
#    ports:
#      - '8002:8025'


